// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BroadcastState() {
  return window['go']['app']['App']['BroadcastState']();
}

export function GetState() {
  return window['go']['app']['App']['GetState']();
}

export function LoadYAMLSettings(arg1) {
  return window['go']['app']['App']['LoadYAMLSettings'](arg1);
}

export function SelectProjectDirectory() {
  return window['go']['app']['App']['SelectProjectDirectory']();
}

export function SetState(arg1, arg2) {
  return window['go']['app']['App']['SetState'](arg1, arg2);
}

export function StartAnalyzer() {
  return window['go']['app']['App']['StartAnalyzer']();
}

export function StartInteractiveBrowser() {
  return window['go']['app']['App']['StartInteractiveBrowser']();
}
