// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {state} from '../models';
import {settings} from '../models';

export function BroadcastState():Promise<void>;

export function GetState():Promise<state.RemoteState>;

export function LoadYAMLSettings(arg1:string):Promise<settings.Settings>;

export function SelectProjectDirectory():Promise<string>;

export function SetState(arg1:state.RemoteState):Promise<state.RemoteState>;

export function StartAnalyzer():Promise<void>;

export function StartInteractiveBrowser():Promise<void>;
