// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function LoadYAMLSettings(arg1:string):Promise<settings.Settings>;

export function Run():Promise<string>;

export function SelectProjectDirectory():Promise<string>;

export function StartInteractiveBrowser(arg1:string):Promise<void>;

export function StopInteractiveBrowser(arg1:string):Promise<boolean>;
