// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadYAMLSettings(arg1) {
  return window['go']['main']['App']['LoadYAMLSettings'](arg1);
}

export function Run() {
  return window['go']['main']['App']['Run']();
}

export function SelectProjectDirectory() {
  return window['go']['main']['App']['SelectProjectDirectory']();
}

export function StartInteractiveBrowser(arg1) {
  return window['go']['main']['App']['StartInteractiveBrowser'](arg1);
}

export function StopInteractiveBrowser(arg1) {
  return window['go']['main']['App']['StopInteractiveBrowser'](arg1);
}
