// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {settings} from '../models';

export function AppendLog(arg1:main.LogEntry):Promise<void>;

export function BroadcastState():Promise<void>;

export function GetState():Promise<main.AppState>;

export function LoadYAMLSettings(arg1:string):Promise<settings.Settings>;

export function SelectProjectDirectory():Promise<string>;

export function SetState(arg1:main.AppState,arg2:number):Promise<main.AppState>;

export function StartInteractiveBrowser():Promise<void>;

export function StopInteractiveBrowser(arg1:string):Promise<boolean>;
